#cloud-config
users:
  - name: adminuser
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: docker
package_update: true
packages:
  - docker.io
runcmd:
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker adminuser